version: '3'

services:
  pulsar:
    restart: always
    image: apachepulsar/pulsar:2.8.1
    ports:
      - "6650:6650"
      - "8080:8080"
    command: >
      /bin/bash -c "bin/pulsar standalone"

  redis:
    restart: always
    image: redis:6.0.8
    ports:
      - "6379:6379"
    environment:
      - DEBUG=false
