version: '3.6'

networks:
  dev-trading-net: {}

services:
  pulsar:
    restart: always
    image: apachepulsar/pulsar:2.8.1
    ports:
      - "6650:6650"
      - "8080:8080"
    command: >
      /bin/bash -c "bin/pulsar standalone"
    networks:
      - dev-trading-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/admin/v2/brokers/health"]
      interval: 2s
      timeout: 5s
      retries: 15
      start_period: 2m

  pulsar-manager:
    restart: always
    image: apachepulsar/pulsar-manager:v0.2.0
    ports:
      - "9527:9527"
      - "7750:7750"
    networks:
      - dev-trading-net
    depends_on:
      pulsar:
        condition: service_healthy
    volumes:
      - ../pulsar-manager/application.properties:/pulsar-manager/custom.properties
    environment:
      - SPRING_CONFIGURATION_FILE=/pulsar-manager/custom.properties

  redis:
    restart: always
    image: redis:6.0.8
    ports:
      - "6379:6379"
    networks:
      - dev-trading-net
    environment:
      - DEBUG=false
